name: Java CI (No Maven/Gradle)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JUnit
        run: |
          mkdir libs
          curl -L -o libs/junit-4.13.2.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
          curl -L -o libs/hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      - name: Compile Java files
        run: |
          mkdir -p out
          javac -cp "libs/*" -d out $(find src test -name "*.java")

      - name: Run JUnit tests
        run: |
          java -cp "out:libs/*" org.junit.runner.JUnitCore имя_тестового_класса